### ISSUE TITLE
adding location, url and attendees.

### ISSUE THREAD

**Issue by panigrah** [PeronGH/simple-ics#1]
Hi, are you planning to add in the missing fields? thanks

**Comment by PeronGH** [comment]
Yes, I can add more fields when I have time, but this repo was just a toy for me and not suitable for any production use.

**Comment by panigrah** [comment]
added the fields I needed - if you are comfortable with the pull request please go ahead and merge them. thanks

**Comment by PeronGH** [comment]
thanks a lot
